import { TrainingPlan, IntervalWorkout } from '@/lib/types';

// ============ TRAINING PLANS ============

export const TRAINING_PLANS: TrainingPlan[] = [
    {
        id: 'couch_to_5k',
        name: 'Couch to 5K',
        description: 'Go from zero to running 5km in 8 weeks. Perfect for absolute beginners.',
        difficulty: 'beginner',
        duration_weeks: 8,
        icon: '🛋️',
        weeks: [
            {
                week: 1, label: 'Getting Started',
                days: [
                    { day: 1, type: 'easy', description: 'Walk 5 min, jog 1 min × 4, walk 5 min', duration_min: 20 },
                    { day: 2, type: 'rest', description: 'Rest or light stretching' },
                    { day: 3, type: 'easy', description: 'Walk 5 min, jog 1 min × 5, walk 5 min', duration_min: 20 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Walk 5 min, jog 1 min × 5, walk 5 min', duration_min: 20 },
                    { day: 6, type: 'cross', description: 'Walk, swim, or cycle (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 2, label: 'Building Confidence',
                days: [
                    { day: 1, type: 'easy', description: 'Walk 3 min, jog 2 min × 5', duration_min: 25 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Walk 3 min, jog 2 min × 5', duration_min: 25 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Walk 2 min, jog 3 min × 4', duration_min: 25 },
                    { day: 6, type: 'cross', description: 'Cross-training (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 3, label: 'Longer Intervals',
                days: [
                    { day: 1, type: 'easy', description: 'Warm up, jog 3 min, walk 2 min × 5', duration_min: 25 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Warm up, jog 4 min, walk 2 min × 4', duration_min: 28 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Warm up, jog 4 min, walk 1 min × 4', duration_min: 25 },
                    { day: 6, type: 'cross', description: 'Cross-training (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 4, label: 'Steady Progress',
                days: [
                    { day: 1, type: 'easy', description: 'Warm up, jog 5 min × 3 with 2 min walks', duration_min: 25 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Warm up, jog 8 min, walk 3 min, jog 8 min', duration_min: 25 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Warm up, jog 10 min, walk 2 min, jog 5 min', duration_min: 25 },
                    { day: 6, type: 'cross', description: 'Cross-training (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 5, label: 'Big Breakthrough',
                days: [
                    { day: 1, type: 'easy', description: 'Warm up, jog 10 min, walk 2 min, jog 10 min', duration_min: 28 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'tempo', description: 'Warm up, jog 15 min non-stop, cool down', duration_min: 25 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'tempo', description: '🎯 Warm up, jog 20 min non-stop!', duration_min: 30 },
                    { day: 6, type: 'cross', description: 'Cross-training (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 6, label: 'Running Longer',
                days: [
                    { day: 1, type: 'easy', description: 'Warm up, jog 22 min, cool down', duration_min: 30 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Warm up, jog 25 min, cool down', duration_min: 33 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Warm up, jog 25 min, cool down', duration_min: 33 },
                    { day: 6, type: 'cross', description: 'Cross-training (30 min)', duration_min: 30 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 7, label: 'Almost There',
                days: [
                    { day: 1, type: 'easy', description: 'Warm up, jog 25 min, cool down', duration_min: 33 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Warm up, jog 28 min, cool down', duration_min: 36 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'long', description: 'Warm up, jog 30 min (~4km), cool down', distance_km: 4, duration_min: 38 },
                    { day: 6, type: 'cross', description: 'Cross-training (20 min)', duration_min: 20 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 8, label: '🎉 Race Week!',
                days: [
                    { day: 1, type: 'easy', description: 'Easy jog 20 min', duration_min: 25 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Easy jog 15 min', duration_min: 20 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'rest', description: 'Pre-race rest' },
                    { day: 6, type: 'long', description: '🏁 Run your 5K!', distance_km: 5, duration_min: 35 },
                    { day: 7, type: 'rest', description: 'Celebrate! 🎊' },
                ],
            },
        ],
    },
    {
        id: '10k_prep',
        name: '10K Race Prep',
        description: 'Train for a 10K race in 6 weeks. Must be able to run 5K comfortably.',
        difficulty: 'intermediate',
        duration_weeks: 6,
        icon: '🏃',
        weeks: [
            {
                week: 1, label: 'Base Building',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 3km', distance_km: 3, duration_min: 20 },
                    { day: 2, type: 'rest', description: 'Rest or walk' },
                    { day: 3, type: 'tempo', description: 'Tempo run 3km at moderate effort', distance_km: 3, duration_min: 18 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'easy', description: 'Easy run 4km', distance_km: 4, duration_min: 25 },
                    { day: 6, type: 'long', description: 'Long run 5km', distance_km: 5, duration_min: 35 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 2, label: 'Adding Speed',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 4km', distance_km: 4, duration_min: 25 },
                    { day: 2, type: 'interval', description: '5 × 400m fast with 200m jog recovery', duration_min: 30 },
                    { day: 3, type: 'rest', description: 'Rest day' },
                    { day: 4, type: 'tempo', description: 'Tempo run 4km', distance_km: 4, duration_min: 22 },
                    { day: 5, type: 'rest', description: 'Rest day' },
                    { day: 6, type: 'long', description: 'Long run 6km', distance_km: 6, duration_min: 40 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 3, label: 'Building Volume',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 4km', distance_km: 4, duration_min: 25 },
                    { day: 2, type: 'interval', description: '6 × 400m fast with 200m recovery', duration_min: 35 },
                    { day: 3, type: 'rest', description: 'Rest day' },
                    { day: 4, type: 'tempo', description: 'Tempo run 5km', distance_km: 5, duration_min: 28 },
                    { day: 5, type: 'rest', description: 'Rest day' },
                    { day: 6, type: 'long', description: 'Long run 8km', distance_km: 8, duration_min: 50 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 4, label: 'Peak Week',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 5km', distance_km: 5, duration_min: 30 },
                    { day: 2, type: 'interval', description: '4 × 800m fast with 400m recovery', duration_min: 35 },
                    { day: 3, type: 'rest', description: 'Rest day' },
                    { day: 4, type: 'tempo', description: 'Tempo run 5km at race pace', distance_km: 5, duration_min: 27 },
                    { day: 5, type: 'rest', description: 'Rest day' },
                    { day: 6, type: 'long', description: 'Long run 10km (test run!)', distance_km: 10, duration_min: 60 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 5, label: 'Recovery + Speed',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 4km', distance_km: 4, duration_min: 25 },
                    { day: 2, type: 'interval', description: '3 × 1km at race pace with 500m jog', duration_min: 30 },
                    { day: 3, type: 'rest', description: 'Rest day' },
                    { day: 4, type: 'tempo', description: 'Tempo run 4km', distance_km: 4, duration_min: 22 },
                    { day: 5, type: 'rest', description: 'Rest day' },
                    { day: 6, type: 'long', description: 'Long run 8km', distance_km: 8, duration_min: 48 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 6, label: '🏁 Race Week!',
                days: [
                    { day: 1, type: 'easy', description: 'Easy shakeout 3km', distance_km: 3, duration_min: 18 },
                    { day: 2, type: 'rest', description: 'Rest day' },
                    { day: 3, type: 'easy', description: 'Easy jog 2km + strides', distance_km: 2, duration_min: 15 },
                    { day: 4, type: 'rest', description: 'Rest day' },
                    { day: 5, type: 'rest', description: 'Pre-race rest (hydrate!)' },
                    { day: 6, type: 'long', description: '🏁 Race day! Run your 10K!', distance_km: 10 },
                    { day: 7, type: 'rest', description: 'Celebrate! 🎊' },
                ],
            },
        ],
    },
    {
        id: 'half_marathon',
        name: 'Half Marathon Prep',
        description: 'Train for 21.1km in 10 weeks. Must be comfortable running 10K.',
        difficulty: 'advanced',
        duration_weeks: 10,
        icon: '🏅',
        weeks: [
            {
                week: 1, label: 'Foundation',
                days: [
                    { day: 1, type: 'easy', description: 'Easy run 5km', distance_km: 5, duration_min: 30 },
                    { day: 2, type: 'tempo', description: 'Tempo 4km', distance_km: 4, duration_min: 22 },
                    { day: 3, type: 'rest', description: 'Rest' },
                    { day: 4, type: 'easy', description: 'Easy run 6km', distance_km: 6, duration_min: 35 },
                    { day: 5, type: 'rest', description: 'Rest' },
                    { day: 6, type: 'long', description: 'Long run 10km', distance_km: 10, duration_min: 60 },
                    { day: 7, type: 'rest', description: 'Full rest' },
                ],
            },
            {
                week: 2, label: 'Build Up', days: [
                    { day: 1, type: 'easy', description: 'Easy 5km', distance_km: 5 }, { day: 2, type: 'interval', description: '6×400m', duration_min: 30 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'tempo', description: 'Tempo 5km', distance_km: 5 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 12km', distance_km: 12 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 3, label: 'Increasing Distance', days: [
                    { day: 1, type: 'easy', description: 'Easy 6km', distance_km: 6 }, { day: 2, type: 'interval', description: '4×800m', duration_min: 35 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'tempo', description: 'Tempo 5km', distance_km: 5 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 14km', distance_km: 14 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 4, label: 'Recovery', days: [
                    { day: 1, type: 'easy', description: 'Easy 4km', distance_km: 4 }, { day: 2, type: 'rest', description: 'Rest' },
                    { day: 3, type: 'easy', description: 'Easy 5km', distance_km: 5 }, { day: 4, type: 'rest', description: 'Rest' },
                    { day: 5, type: 'easy', description: 'Easy 3km', distance_km: 3 }, { day: 6, type: 'long', description: 'Long 10km', distance_km: 10 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 5, label: 'Peak Training', days: [
                    { day: 1, type: 'easy', description: 'Easy 6km', distance_km: 6 }, { day: 2, type: 'interval', description: '5×800m', duration_min: 35 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'tempo', description: 'Tempo 6km', distance_km: 6 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 16km', distance_km: 16 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 6, label: 'Long Run Focus', days: [
                    { day: 1, type: 'easy', description: 'Easy 5km', distance_km: 5 }, { day: 2, type: 'tempo', description: 'Tempo 5km', distance_km: 5 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'easy', description: 'Easy 6km', distance_km: 6 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 18km', distance_km: 18 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 7, label: 'Peak Distance', days: [
                    { day: 1, type: 'easy', description: 'Easy 5km', distance_km: 5 }, { day: 2, type: 'interval', description: '3×1600m', duration_min: 40 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'tempo', description: 'Tempo 5km', distance_km: 5 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 20km!', distance_km: 20 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 8, label: 'Taper Start', days: [
                    { day: 1, type: 'easy', description: 'Easy 5km', distance_km: 5 }, { day: 2, type: 'tempo', description: 'Tempo 4km', distance_km: 4 },
                    { day: 3, type: 'rest', description: 'Rest' }, { day: 4, type: 'easy', description: 'Easy 4km', distance_km: 4 },
                    { day: 5, type: 'rest', description: 'Rest' }, { day: 6, type: 'long', description: 'Long 14km', distance_km: 14 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 9, label: 'Final Taper', days: [
                    { day: 1, type: 'easy', description: 'Easy 4km', distance_km: 4 }, { day: 2, type: 'rest', description: 'Rest' },
                    { day: 3, type: 'easy', description: 'Easy 3km + strides', distance_km: 3 }, { day: 4, type: 'rest', description: 'Rest' },
                    { day: 5, type: 'easy', description: 'Shakeout 2km', distance_km: 2 }, { day: 6, type: 'long', description: 'Long 8km', distance_km: 8 }, { day: 7, type: 'rest', description: 'Rest' },
                ],
            },
            {
                week: 10, label: '🏁 Race Week!', days: [
                    { day: 1, type: 'easy', description: 'Easy 3km', distance_km: 3 }, { day: 2, type: 'rest', description: 'Rest' },
                    { day: 3, type: 'easy', description: 'Easy 2km', distance_km: 2 }, { day: 4, type: 'rest', description: 'Rest' },
                    { day: 5, type: 'rest', description: 'Pre-race rest' }, { day: 6, type: 'long', description: '🏁 Half Marathon! 21.1km', distance_km: 21.1 }, { day: 7, type: 'rest', description: 'Celebrate! 🏅' },
                ],
            },
        ],
    },
];

// ============ INTERVAL WORKOUTS ============

export const INTERVAL_WORKOUTS: IntervalWorkout[] = [
    {
        id: 'beginner_intervals',
        name: 'Beginner Intervals',
        description: 'Simple run/walk intervals for building fitness',
        icon: '🟢',
        total_duration_seconds: 1200,
        steps: [
            { type: 'warmup', duration_seconds: 300, label: 'Walk warm-up' },
            { type: 'work', duration_seconds: 60, label: 'Jog' },
            { type: 'rest', duration_seconds: 90, label: 'Walk' },
            { type: 'work', duration_seconds: 60, label: 'Jog' },
            { type: 'rest', duration_seconds: 90, label: 'Walk' },
            { type: 'work', duration_seconds: 60, label: 'Jog' },
            { type: 'rest', duration_seconds: 90, label: 'Walk' },
            { type: 'work', duration_seconds: 60, label: 'Jog' },
            { type: 'rest', duration_seconds: 90, label: 'Walk' },
            { type: 'cooldown', duration_seconds: 300, label: 'Walk cool-down' },
        ],
    },
    {
        id: 'speed_builder',
        name: 'Speed Builder',
        description: '30/30 intervals to build speed and VO2max',
        icon: '⚡',
        total_duration_seconds: 1500,
        steps: [
            { type: 'warmup', duration_seconds: 300, label: 'Easy jog warm-up' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'work', duration_seconds: 30, label: '🔥 Sprint!' },
            { type: 'rest', duration_seconds: 30, label: 'Easy jog' },
            { type: 'cooldown', duration_seconds: 300, label: 'Easy jog cool-down' },
        ],
    },
    {
        id: 'pyramid',
        name: 'Pyramid',
        description: 'Increasing then decreasing intervals for endurance',
        icon: '🔺',
        total_duration_seconds: 2100,
        steps: [
            { type: 'warmup', duration_seconds: 300, label: 'Easy jog warm-up' },
            { type: 'work', duration_seconds: 60, label: 'Fast pace (1 min)' },
            { type: 'rest', duration_seconds: 60, label: 'Recovery jog' },
            { type: 'work', duration_seconds: 120, label: 'Fast pace (2 min)' },
            { type: 'rest', duration_seconds: 60, label: 'Recovery jog' },
            { type: 'work', duration_seconds: 180, label: 'Fast pace (3 min)' },
            { type: 'rest', duration_seconds: 90, label: 'Recovery jog' },
            { type: 'work', duration_seconds: 120, label: 'Fast pace (2 min)' },
            { type: 'rest', duration_seconds: 60, label: 'Recovery jog' },
            { type: 'work', duration_seconds: 60, label: 'Fast pace (1 min)' },
            { type: 'cooldown', duration_seconds: 300, label: 'Easy jog cool-down' },
        ],
    },
    {
        id: 'tabata',
        name: 'Tabata Sprints',
        description: '20s max effort / 10s rest × 8. Brutal but effective!',
        icon: '💀',
        total_duration_seconds: 840,
        steps: [
            { type: 'warmup', duration_seconds: 300, label: 'Easy jog warm-up' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'work', duration_seconds: 20, label: '💀 MAX EFFORT!' },
            { type: 'rest', duration_seconds: 10, label: 'Rest' },
            { type: 'cooldown', duration_seconds: 300, label: 'Walk cool-down' },
        ],
    },
    {
        id: 'tempo_builder',
        name: 'Tempo Builder',
        description: 'Sustained tempo efforts for race-day pacing',
        icon: '🎯',
        total_duration_seconds: 2400,
        steps: [
            { type: 'warmup', duration_seconds: 300, label: 'Easy jog warm-up' },
            { type: 'work', duration_seconds: 300, label: 'Tempo pace (5 min)' },
            { type: 'rest', duration_seconds: 120, label: 'Easy jog' },
            { type: 'work', duration_seconds: 300, label: 'Tempo pace (5 min)' },
            { type: 'rest', duration_seconds: 120, label: 'Easy jog' },
            { type: 'work', duration_seconds: 300, label: 'Tempo pace (5 min)' },
            { type: 'rest', duration_seconds: 120, label: 'Easy jog' },
            { type: 'cooldown', duration_seconds: 300, label: 'Easy jog cool-down' },
        ],
    },
];
